{
 "title": "Steps Summary",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "runID", "label": "RunID" },
   { "name": "Scenario", "label": "Scenario" }
  ]
 },
 "panels": [
  {
   "title": "Execution Environment",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "target": "MetaData", "type": "table" }
   ]
  },
  {
   "title": "Steps Summary",
   "type": "table",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 3 },
   "targets": [
    { "target": "StepsRun", "type": "table" }
   ]
  },
  {
   "title": "Execution Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 3 },
   "targets": [
    { "target": "StepDetails", "type": "table" }
   ]
  }
 ]
}